spring:
  application:
    name: audit-web
  profiles:
    active: dev


server:
  port: 12080

logging:
  config: config/logback.xml

eureka:
  client:
    register-with-eureka: true
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 9


---
spring:
  profiles: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/audit?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
global-config:
  server-url: http://localhost:9080/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: qa
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.0.20.202:3306/audit?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: audit_test
    password: audit_test
    driver-class-name: com.mysql.jdbc.Driver
global-config:
  server-url: http://localhost:9080/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/audit?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
global-config:
  server-url: http://localhost:9080/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
